export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  VICE_PRINCIPAL = 'VICE_PRINCIPAL',
  HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT',
  TEACHER = 'TEACHER',
  CLASS_TEACHER = 'CLASS_TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  ACCOUNTANT = 'ACCOUNTANT',
  LIBRARIAN = 'LIBRARIAN',
  RECEPTIONIST = 'RECEPTIONIST',
  SUPPORT_STAFF = 'SUPPORT_STAFF',
}

export const ADMIN_ROLES: Role[] = [
  Role.SUPER_ADMIN,
  Role.SCHOOL_ADMIN,
  Role.PRINCIPAL,
  Role.VICE_PRINCIPAL,
];

export const STAFF_ROLES: Role[] = [
  Role.HEAD_OF_DEPARTMENT,
  Role.TEACHER,
  Role.CLASS_TEACHER,
  Role.ACCOUNTANT,
  Role.LIBRARIAN,
  Role.RECEPTIONIST,
  Role.SUPPORT_STAFF,
];
